source $VIMRUNTIME/defaults.vim

" Disable annoying defaults
nnoremap q: <nop>
nnoremap Q <nop>

" Useful mappings
nnoremap Y y$

" visuals
syntax enable

set nu
set nowrap
set timeoutlen=1000 ttimeoutlen=0
set hidden
set completeopt=longest,menuone
set wildmode=longest,list

" always enable autoindenting

set noswapfile
