- name: Look up binary
  ansible.builtin.stat:
    path: "{{ install_path }}/helm{{ helm_version }}"
  register: helm_stat

- name: Install
  block:
    - name: Create temp dir
      ansible.builtin.tempfile:
        state: directory
      register: tmp_dir

    - name: Fetch helm
      ansible.builtin.unarchive:
        src: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
        remote_src: true
        dest: "{{ tmp_dir.path }}"

    - name: Move binary
      ansible.builtin.copy:
        src: "{{ tmp_dir.path }}/linux-amd64/helm"
        remote_src: true
        dest: "{{ install_path }}/helm{{ helm_version }}"
        mode: 0755

    - name: Create symlink
      ansible.builtin.file:
        state: link
        src: "{{ install_path }}/helm{{ helm_version }}"
        dest: "{{ install_path }}/helm"
  when: not helm_stat.stat.exists
