- name: Look up binary
  ansible.builtin.stat:
    path: "{{ install_path }}/k9s{{ k9s_version }}"
  register: k9s_stat

- name: Install
  block:
    - name: Create temp dir
      ansible.builtin.tempfile:
        state: directory
      register: tmp_dir

    - name: Fetch k9s
      ansible.builtin.unarchive:
        src: "https://github.com/derailed/k9s/releases/download/v{{ k9s_version }}/k9s_Linux_amd64.tar.gz"
        remote_src: true
        dest: "{{ tmp_dir.path }}"

    - name: Move binary
      ansible.builtin.copy:
        src: "{{ tmp_dir.path }}/k9s"
        remote_src: true
        dest: "{{ install_path }}/k9s{{ k9s_version }}"
        mode: 0755

    - name: Create symlink
      ansible.builtin.file:
        state: link
        src: "{{ install_path }}/k9s{{ k9s_version }}"
        dest: "{{ install_path }}/k9s"
  when: not k9s_stat.stat.exists
