- name: Fetch kind
  ansible.builtin.uri:
    url: "https://github.com/kubernetes-sigs/kind/releases/download/v{{ kind_version }}/kind-linux-amd64"
    dest: "{{ install_path }}/kind{{ kind_version }}"
    creates: "{{ install_path }}/kind{{ kind_version }}"
    mode: 0755
  register: kind_fetch

- name: Create symlink
  ansible.builtin.file:
    state: link
    src: "{{ install_path }}/kind{{ kind_version }}"
    dest: "{{ install_path }}/kind"
  when: kind_fetch.changed
