- name: Look up binary
  ansible.builtin.stat:
    path: "{{ install_path }}/terraform{{ terraform_version }}"
  register: terraform_stat

- name: Install
  block:
    - name: Create temp dir
      ansible.builtin.tempfile:
        state: directory
      register: tmp_dir

    - name: Fetch terraform
      ansible.builtin.unarchive:
        src: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
        remote_src: true
        dest: "{{ tmp_dir.path }}"

    - name: Move binary
      ansible.builtin.copy:
        src: "{{ tmp_dir.path }}/terraform"
        remote_src: true
        dest: "{{ install_path }}/terraform{{ terraform_version }}"
        mode: 0755

    - name: Create symlink
      ansible.builtin.file:
        state: link
        src: "{{ install_path }}/terraform{{ terraform_version }}"
        dest: "{{ install_path }}/terraform"
  when: not terraform_stat.stat.exists
