- name: Fetch vcluster
  ansible.builtin.uri:
    url: "https://github.com/loft-sh/vcluster/releases/download/v{{ vcluster_version }}/vcluster-linux-amd64"
    dest: "{{ install_path }}/vcluster{{ vcluster_version }}"
    creates: "{{ install_path }}/vcluster{{ vcluster_version }}"
    mode: 0755
  register: vcluster_fetch

- name: Create symlink
  ansible.builtin.file:
    state: link
    src: "{{ install_path }}/vcluster{{ vcluster_version }}"
    dest: "{{ install_path }}/vcluster"
  when: vcluster_fetch.changed
