- name: Look up binary
  ansible.builtin.stat:
    path: "{{ install_path }}/zed{{ zed_version }}"
  register: zed_stat

- name: Install
  block:
    - name: Create temp dir
      ansible.builtin.tempfile:
        state: directory
      register: tmp_dir

    - name: Fetch zed
      ansible.builtin.unarchive:
        src: "https://github.com/zed-industries/zed/releases/download/v{{ zed_version }}/zed-linux-aarch64.tar.gz"
        remote_src: true
        dest: "{{ tmp_dir.path }}"

    - name: Move binary
      ansible.builtin.copy:
        src: "{{ tmp_dir.path }}/zed.app/bin/zed"
        remote_src: true
        dest: "{{ install_path }}/zed{{ zed_version }}"
        mode: 0755

    - name: Create symlink
      ansible.builtin.file:
        state: link
        src: "{{ install_path }}/zed{{ zed_version }}"
        dest: "{{ install_path }}/zed"
  when: not zed_stat.stat.exists
